# Generated by Django 4.2.6 on 2023-10-05 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_paymentbills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма')),
                ('operation_type', models.CharField(choices=[('depositing', 'зачисление'), ('writing_off', 'списание')], verbose_name='тип операции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время')),
                ('description', models.TextField(verbose_name='описание')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.botuser', verbose_name='юзер')),
            ],
            options={
                'verbose_name': 'транзакция',
                'verbose_name_plural': 'транзакции',
                'ordering': ['-id'],
            },
        ),
    ]
