# Generated by Django 4.2.6 on 2023-10-05 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='баланс')),
                ('bot_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.botuser', verbose_name='юзер')),
            ],
            options={
                'verbose_name': 'профиль юзера',
                'verbose_name_plural': 'профили пользователей',
                'ordering': ['-id'],
            },
        ),
    ]
