# Generated by Django 4.2.6 on 2023-10-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbills',
            name='bill_hash',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='хэш'),
        ),
    ]
