# Generated by Django 4.2.6 on 2023-10-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_paymentbills_bill_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentbills',
            name='status',
            field=models.CharField(choices=[('created', 'создан'), ('on_check', 'на проверке'), ('payed', 'оплачен'), ('decline', 'отклонен'), ('close_without_pay', 'закрыт без оплаты')], default='created', verbose_name='статус'),
        ),
    ]
