# Generated by Django 4.2.6 on 2023-10-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_paymentbills_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('link', models.URLField(verbose_name='ссылка')),
                ('group_tlg_id', models.CharField(max_length=200, verbose_name='TG ID чата')),
                ('msg_text', models.TextField(verbose_name='текст сообщения')),
                ('tag_now', models.BooleanField(default=False, verbose_name='тегать сразу')),
                ('bot_rights_checked', models.BooleanField(default=False, verbose_name='права бота проверены')),
                ('in_work', models.BooleanField(default=False, verbose_name='в работе')),
                ('paid_by', models.DateTimeField(blank=True, null=True, verbose_name='оплачена до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='когда создана')),
            ],
            options={
                'verbose_name': 'групповой чат',
                'verbose_name_plural': 'групповые чаты',
                'ordering': ['-id'],
            },
        ),
    ]
