# Generated by Django 4.2.6 on 2023-10-10 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_groupchats'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchats',
            name='bot_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.botuser', verbose_name='владелец'),
            preserve_default=False,
        ),
    ]
