# Generated by Django 4.2.6 on 2023-10-10 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_groupchats_bot_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='group_chats', verbose_name='файл')),
                ('group_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.groupchats', verbose_name='групповой чат')),
            ],
        ),
    ]
