# Generated by Django 4.2.6 on 2023-10-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_groupchatfiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchatfiles',
            options={'ordering': ['-id'], 'verbose_name': 'файлы для гр.чата', 'verbose_name_plural': 'файлы для гр.чатов'},
        ),
    ]
