# Generated by Django 4.2.6 on 2023-10-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_groupchats_group_tlg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatfiles',
            name='file_name',
            field=models.CharField(blank=True, null=True, verbose_name='имя'),
        ),
    ]
