# Generated by Django 4.2.6 on 2023-10-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_rename_group_tlg_id_groupchats_group_tg_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='фамилия'),
        ),
    ]
