# Generated by Django 4.2.6 on 2023-10-24 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_botuser_firstname_botuser_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='bot_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='webapp.botuser', verbose_name='юзер'),
        ),
    ]
